steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/${PROJECT_ID}/html-to-file-api:${COMMIT_SHA}',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/html-to-file-api:${COMMIT_SHA}']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'html-to-file-api',
        '--image',
        'gcr.io/${PROJECT_ID}/html-to-file-api:${COMMIT_SHA}',
        '--platform',
        'managed',
        '--region',
        'asia-southeast1',
        '--allow-unauthenticated',
        '--memory',
        '1Gi',
        '--cpu',
        '1',
        '--timeout',
        '90s',
        '--set-env-vars',
        'JWT_SECRET=projects/${PROJECT_NUMBER}/secrets/JWT_SECRET_KEY',
        '--update-secrets',
        'JWT_SECRET=projects/${PROJECT_NUMBER}/secrets/JWT_SECRET_KEY',
        '--set-env-vars',
        'ENVIRONMENT=production',
      ]
images:
  - 'gcr.io/${PROJECT_ID}/html-to-file-api:${COMMIT_SHA}'
